#   Title: dockerfile
#   Author: Ramirez de Diego, Jorge
#   Date: 2024
#   Code version: 1.0
#   Availability: https://github.com/JRamirezDD/TutorLink

FROM openjdk:21-slim AS build

WORKDIR /app

COPY build.gradle settings.gradle /app/

COPY gradlew /app/
COPY gradle /app/gradle

COPY src /app/src

RUN ./gradlew build -x test --stacktrace

FROM openjdk:21-slim
LABEL authors="jorge"

ENV SPRING_APPLICATION_NAME=student-domain-functional
ENV SERVER_ADDRESS=0.0.0.0
ENV SERVER_PORT=10000

EXPOSE $SERVER_PORT

COPY --from=build /app/build/libs/functional-0.0.1-SNAPSHOT.jar /app/functional-0.0.1-SNAPSHOT.jar

WORKDIR /app
ENTRYPOINT ["java", "-jar", "/app/functional-0.0.1-SNAPSHOT.jar"]