server:
  address: ${STUDENT_DOMAIN_SERVICES_AUTH_SERVICE_ADDRESS:localhost}
  port: ${STUDENT_DOMAIN_SERVICES_AUTH_SERVICE_PORT:10019}

spring:
    application:
      name: student-domain-auth
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ''
              client-secret: ''
              scope:
                - profile
                - email
              redirect-uri: ${STUDENT_DOMAIN_SERVICES_GATEWAY_URL:http://localhost}:${STUDENT_DOMAIN_SERVICES_GATEWAY_PORT:10010}/gateway/authentication/google-login
              client-name: Google
              authorization-grant-type: authorization_code
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: id

    datasource:
      url: ${STUDENT_DOMAIN_DATASOURCE_URL:jdbc:postgresql://localhost:5432}/${STUDENT_DOMAIN_SPRING_DATASOURCE_DATABASE:student_db}
      username: ${STUDENT_DOMAIN_DATASOURCE_USERNAME:main_user}
      password: ${STUDENT_DOMAIN_DATASOURCE_PASSWORD:PassWord12@}
      driver-class-name: ${STUDENT_DOMAIN_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    jpa:
      hibernate:
        ddl-auto: ${STUDENT_DOMAIN_JPA_HIBERNATE_DDL_AUTO:update}
      show-sql: true
      properties:
        hibernate:
          default_schema: ${STUDENT_DOMAIN_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:student_auth_schema}
      open-in-view: ${STUDENT_DOMAIN_JPA_OPEN_IN_VIEW:true}


session:
  token-expiry: 1800

logging:
  level:
    org:
      springframework:
        web: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:DEBUG}
