server:
  port: 10019
  address: "http://localhost"

spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ''
              client-secret: ''
              scope:
                - profile
                - email
              redirect-uri: http://localhost:10010/authentication/google-login
              client-name: Google
              authorization-grant-type: authorization_code
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: id

    datasource:
      url: ${STUDENT_DOMAIN_SPRING_DATASOURCE_URL:jdbc:postgresql://student-db:5432/student_db}
      username: ${STUDENT_DOMAIN_SPRING_DATASOURCE_USERNAME:main_user}
      password: ${STUDENT_DOMAIN_SPRING_DATASOURCE_PASSWORD:PassWord12@}
      driver-class-name: ${STUDENT_DOMAIN_SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    jpa:
      hibernate:
        ddl-auto: ${STUDENT_DOMAIN_SPRING_JPA_HIBERNATE_DDL_AUTO:update}
      show-sql: ${STUDENT_DOMAIN_SPRING_JPA_SHOW_SQL:true}
      properties:
        hibernate:
          default_schema: ${STUDENT_DOMAIN_SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:student_schema}
      open-in-view: ${STUDENT_DOMAIN_SPRING_JPA_OPEN_IN_VIEW:true}


session:
  token-expiry: 1800

