logging:
  level:
    org.springframework.web: "DEBUG"

student_domain:
  datasource:
    url: "jdbc:postgresql://student-db:5432"
    database: "student_db"
    username: "main_user"
    password: "PassWord12@"
    driver-class-name: "org.postgresql.Driver"

    jpa:
      hibernate:
        ddl-auto: "update"

  services:
    ui:
      address: "0.0.0.0"
      url: "http://localhost"
      port: 80
    gateway:
      address: "0.0.0.0"
      url: "http://student-domain-gateway"
      port: 10010
    functional_service:
      address: "0.0.0.0"
      url: "http://student-domain-functional"
      port: 10011
      database:
        default_schema: "student_schema"
    auth_service:
      url: "http://student-domain-auth"
      port: 10019
      database:
        default_schema: "student_auth_schema"

tutor_domain:
  datasource:
    url: "jdbc:postgresql://tutor-db:5432"
    database: "tutor_db"
    username: "main_user"
    password: "PassWord12@"
    jpa:
      hibernate:
        ddl-auto: "update"

  services:
    gateway:
      address: "0.0.0.0"
      url: "http://tutor-domain-gateway"
      port: 30010
    functional_service:
      address: "0.0.0.0"
      url: "http://tutor-domain-functional"
      port: 30011
    database:
      default_schema: "tutor_schema"
    auth_service:
      url: "http://student-domain-auth"
      port: 30019
      database:
        default_schema: "tutor_auth_schema"

matchmaking_domain:
  datasource:
    url: "jdbc:postgresql://matchmaking-db:5432"
    database: "matchmaking_db"
    username: "main_user"
    password: "PassWord12@"
    driver-class-name: "org.postgresql.Driver"

    jpa:
      hibernate:
        ddl-auto: "update"

  services:
    gateway:
      address: "0.0.0.0"
      url: "http://matchmaking-domain-gateway"
      port: 20010
    cross_domain_interactions:
      address: "0.0.0.0"
      url: "http://cross-domain-interactions"
      port: 20011
      database:
        default_schema: "cross_domain_interactions_schema"
    student_domain_manager:
      address: "0.0.0.0"
      url: "http://student-domain-manager"
      port: 20012
    tutor_domain_manager:
      address: "0.0.0.0"
      url: "http://tutor-domain-manager"
      port: 20013
      database:
        default_schema: "tutor_domain_manager_schema"
