logging:
  level:
    org.springframework.web: "DEBUG"

student_domain:
  spring:
    datasource:
      url: "jdbc:postgresql://student-db:5432/student_db"
      username: "main_user"
      password: "PassWord12@"
      driver-class-name: "org.postgresql.Driver"

    jpa:
      hibernate:
        ddl-auto: "update"
      show-sql: true
      properties:
        hibernate:
          default-schema: "student_schema"
      open-in-view: true

  services:
    ui:
      address: "0.0.0.0"
      url: "http://localhost"
      port: 80
    logic_gateway:
      address: "0.0.0.0"
      url: "http://student-domain-gateway"
      port: 10010
    functional_service:
      address: "0.0.0.0"
      url: "http://student-domain-functional"
      port: 10011
    auth_service:
      url: "http://student-domain-auth"
      port: 10012

tutor_domain_services:
  logic_gateway:
    address: "0.0.0.0"
    url: "http://localhost"
    port: 30010

matchmaking_domain_services:
  logic_gateway:
    url: "http://localhost"
    port: 20010
