# STUDENT DOMAIN
# STUDENT_DOMAIN_SERVICES_FUNCTIONAL_SERVICE
server:
  address: ${TUTOR_DOMAIN_SERVICES_FUNCTIONAL_SERVICE_ADDRESS:localhost}
  port: ${TUTOR_DOMAIN_SERVICES_FUNCTIONAL_SERVICE_PORT:30011}

logging:
  level:
    org:
      springframework:
        web: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:DEBUG}

spring:
  application:
    name: tutor-domain-functional
  datasource:
    url: ${TUTOR_DOMAIN_DATASOURCE_URL:jdbc:postgresql://localhost:5432}/${TUTOR_DOMAIN_DATASOURCE_DATABASE:tutor_db}
    username: ${TUTOR_DOMAIN_DATASOURCE_USERNAME:main_user}
    password: ${TUTOR_DOMAIN_DATASOURCE_PASSWORD:PassWord12@}
    driver-class-name: ${TUTOR_DOMAIN_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${TUTOR_DOMAIN_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: ${TUTOR_DOMAIN_SERVICES_FUNCTIONAL_SERVICE_DATABASE_DEFAULT_SCHEMA:tutor_schema}


student_domain:
  services:
    gateway:
      address: ${STUDENT_DOMAIN_SERVICES_GATEWAY_ADDRESS:0.0.0.0}
      url: ${STUDENT_DOMAIN_SERVICES_GATEWAY_URL:http://student-domain-gateway}
      port: ${STUDENT_DOMAIN_SERVICES_GATEWAY_PORT:10010}
    functional_service:
      address: ${STUDENT_DOMAIN_SERVICES_FUNCTIONAL_SERVICE_ADDRESS:0.0.0.0}
      url: ${STUDENT_DOMAIN_SERVICES_FUNCTIONAL_SERVICE_URL:http://student-domain-functional}
      port: ${STUDENT_DOMAIN_SERVICES_FUNCTIONAL_SERVICE_PORT:10011}
    auth_service:
      url: ${STUDENT_DOMAIN_SERVICES_AUTH_SERVICE_URL:http://student-domain-auth}
      port: ${STUDENT_DOMAIN_SERVICES_AUTH_SERVICE_PORT:10019}


# Tutor domain configuration, including services and database setup
tutor_domain:
  services:
    gateway:
      url: ${TUTOR_DOMAIN_SERVICES_GATEWAY_URL:http://tutor-domain-gateway}
      port: ${TUTOR_DOMAIN_SERVICES_GATEWAY_PORT:30010}
    functional_service:
      url: ${TUTOR_DOMAIN_SERVICES_FUNCTIONAL_SERVICE_URL:http://tutor-domain-functional}
      port: ${TUTOR_DOMAIN_SERVICES_FUNCTIONAL_SERVICE_PORT:30011}
    auth_service:
      url: ${TUTOR_DOMAIN_SERVICES_AUTH_SERVICE_URL:http://student-domain-auth}
      port: ${TUTOR_DOMAIN_SERVICES_AUTH_SERVICE_PORT:30019}

# Matchmaking domain configuration, including services and database setup
matchmaking_domain_services:
  services:
    gateway:
      url: ${MATCHMAKING_DOMAIN_SERVICES_GATEWAY_URL:http://matchmaking-domain-gateway}
      port: ${MATCHMAKING_DOMAIN_SERVICES_GATEWAY_PORT:20010}
    cross_domain_interactions:
      url: ${MATCHMAKING_DOMAIN_SERVICES_CROSS_DOMAIN_INTERACTIONS_URL:http://cross-domain-interactions/connections}
      port: ${MATCHMAKING_DOMAIN_SERVICES_CROSS_DOMAIN_INTERACTIONS_PORT:20011}
    student_domain_manager:
      url: ${MATCHMAKING_DOMAIN_SERVICES_STUDENT_DOMAIN_MANAGER_URL:http://student-domain-manager}
      port: ${MATCHMAKING_DOMAIN_SERVICES_STUDENT_DOMAIN_MANAGER_PORT:20012}
    tutor_domain_manager:
      url: ${MATCHMAKING_DOMAIN_SERVICES_TUTOR_DOMAIN_MANAGER_URL:http://tutor-domain-manager}
      port: ${MATCHMAKING_DOMAIN_SERVICES_TUTOR_DOMAIN_MANAGER_PORT:20013}