#   Title: dockerfile
#   Author: Ramirez de Diego, Jorge
#   Date: 2024
#   Code version: 1.0
#   Availability: https://github.com/JRamirezDD/TutorLink

# Use compilation image
FROM openjdk:21-slim AS build

# Working directory of container
WORKDIR /app

# Copy gradle files into container
COPY build.gradle settings.gradle /app/

COPY gradlew /app/
COPY gradle /app/gradle

# Copy source code into container
COPY src /app/src

# Build gradle application
RUN ./gradlew build -x test --stacktrace

# Use separate image for runtime
FROM openjdk:21-slim
LABEL authors="jorge"

# Set environment variables
ENV SPRING_APPLICATION_NAME=student-domain-functional
ENV SERVER_ADDRESS=0.0.0.0
ENV SERVER_PORT=10000

# Expose application port
EXPOSE $SERVER_PORT

# Copy compiled application into container
COPY --from=build /app/build/libs/functional-0.0.1-SNAPSHOT.jar /app/functional-0.0.1-SNAPSHOT.jar

# Set working directory
WORKDIR /app

# Run application
ENTRYPOINT ["java", "-jar", "/app/functional-0.0.1-SNAPSHOT.jar"]