#   Title: docker-compose-fullstack.yml
#   Author: Ramirez de Diego, Jorge
#   Date: 2024
#   Code version: 1.0
#   Availability: https://github.com/JRamirezDD/TutorLink

name: tutorlink-fullstack

services:
  ui:
    build:
      context: '../../SourceCode/Frontend/tutorlink_ui'
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ${ENV_FILE}
    networks:
      - tutorlink-network

networks:
  tutorlink-network:
    driver: bridge


