#   Title: docker-compose-fullstack.yml
#   Author: Ramirez de Diego, Jorge
#   Date: 2024
#   Code version: 1.0
#   Availability: https://github.com/JRamirezDD/TutorLink

name: tutorlink-frontend

services:
  ui:
    build:
      context: '../../SourceCode/Frontend/tutorlink_ui'
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ${ENV_FILE}
    networks:
      - tutorlink-network
    volumes:
      # Mount the NGINX configuration file for easy edits
      - ./nginx.conf:/etc/nginx/nginx.conf
      # Persist NGINX logs on the host machine
      - ./logs:/var/log/nginx

networks:
  tutorlink-network:
    driver: bridge


