#   Title: dockerfile
#   Author: Ramirez de Diego, Jorge
#   Date: 2024
#   Code version: 1.0
#   Availability: https://github.com/JRamirezDD/TutorLink

FROM gradle:8.10.2-jdk21-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the entire root context as defined in docker-compose.yml
COPY . .

# Explicitly run Gradle from the root project directory
RUN ./gradlew :Student_Domain:gateway:build --no-daemon -x test

RUN ls -R -la

# Use separate image for runtime
FROM openjdk:21-slim
LABEL authors="jorge"

# Copy the built JAR
COPY --from=build /app/Student_Domain/gateway/build/libs/gateway-*.jar app.jar

# Expose the app port
EXPOSE $SERVER_PORT

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
