name: tryflutter
description: A new Flutter project for building a tutoring application

version: 1.0.0+1

environment:
  sdk: ^3.5.3 # Ensure Dart SDK version is compatible

dependencies:
  json_annotation: ^4.9.0 # Check for the latest version

  flutter:
    sdk: flutter

  # Networking
  flutter_dotenv: ^5.0.2 # Optional: Manage API URLs via environment variables

  # Image Picker
  image_picker: ^0.8.6 # Use the latest stable version

  # Cupertino Icons for iOS
  cupertino_icons: ^1.0.8

  # State Management (Optional, use this if needed)
  provider: ^6.0.4

  tutorlink_frontend_http_package:
    git:
      url: https://github.com/JRamirezDD/TutorLink.git
      ref: main # Optional, specify a branch, tag, or commit
      path: "SourceCode/Frontend/tutorlink_frontend_http_package" # Path within the repository
  intl: ^0.20.1
  shared_preferences: ^2.3.3
  graphql_flutter: ^5.2.0-beta.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_avatar.png
    - assets/images/background.jpg
