name: Gradle execute project tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JVM container
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Navigate to Backend folder
      run: cd SourceCode/Backend
      
    - name: Grant execute permissions for Gradle wrapper
      run: chmod +x SourceCode/Backend/gradlew
      
    - name: Run Gradle tests
      working-directory: SourceCode/Backend
      run: ./gradlew clean test --info
