name: Generate OpenAPI Documentation

on:
  push:
    paths:
      - 'tutorlink/**/*.java'
      - 'tutorlink/pom.xml'
  pull_request:
    paths:
      - 'tutorlink/**/*.java'
      - 'tutorlink/pom.xml'

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project and start Spring Boot application
        run: |
          cd tutorlink
          mvn clean install
          nohup mvn spring-boot:run &
          sleep 30  # Wait for the application to start

      - name: Fetch OpenAPI JSON
        run: |
          mkdir -p ../docs/development/api
          curl -o ../docs/development/api/swaggerStuff.json http://localhost:8080/v3/api-docs
          echo "OpenAPI JSON content:"
          cat ../docs/development/api/swaggerStuff.json  # Print JSON content for troubleshooting
          
      - name: Verify Swagger File Generation
        run: |
          if [ -f docs/development/api/swaggerStuff.json ]; then
            echo "swaggerStuff.json found!"
          else
            echo "swaggerStuff.json not found."
            exit 1
          fi

      - name: Commit and push OpenAPI JSON
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A docs/development/api/swaggerStuff.json
          git checkout -- .
          git clean -fd
          git commit -m "Update OpenAPI documentation [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
